const ADD_CARD = 'ADD_CARD';
const GET_API = 'GET_API';
const ELIMINAR_CARDS = 'ELIMINAR_CARDS';
const ELIMINAR = 'ELIMINAR';
const BUSCAR_CARD = 'BUSCAR_CARD';
const FAVORITES_CARD = 'FAVORITES_CARD'; 
const DELETE_ALL = 'DELETE_ALL';
const DELETE_FAVORITES = 'DELETE_FAVORITES';
const SEARCH_ID = 'SEARCH_ID';

export {
    ADD_CARD,
    GET_API,
    ELIMINAR_CARDS,
    ELIMINAR,
    BUSCAR_CARD,
    FAVORITES_CARD,
    DELETE_ALL,
    DELETE_FAVORITES,
    SEARCH_ID
}