const ADD_CARD = 'ADD_CARD';
const GET_API = 'GET_API';
const ELIMINAR_CARDS = 'ELIMINAR_CARDS';
const ELIMINAR = 'ELIMINAR';
const BUSCAR_CARD = 'BUSCAR_CARD';
const FAVORITES_CARD = 'FAVORITES_CARD'; 
const SHOW_ABOUT_ME = 'SHOW_ABOUT_ME';
const DELETE_ABOUT_ME = 'DELETE_ABOUT_ME';
export {
    ADD_CARD,
    GET_API,
    ELIMINAR_CARDS,
    ELIMINAR,
    BUSCAR_CARD,
    FAVORITES_CARD,
    SHOW_ABOUT_ME,
    DELETE_ABOUT_ME
}