const RANDOM_CARD = 'RANDOM_CARD';
const GET_API = 'GET_API';
const ELIMINAR_CARDS = 'ELIMINAR_CARDS';
const ELIMINAR = 'ELIMINAR';
const BUSCAR_CARD = 'BUSCAR_CARD';

export {
    RANDOM_CARD,
    GET_API,
    ELIMINAR_CARDS,
    ELIMINAR,
    BUSCAR_CARD
}